=== MikelTESP/Lenguaje-de-Marcas/Panel.dtd
<!-- 
Nombre: [MikelTorremocha] 
Curso: [DAM 1] 
Fecha: [2/4/2025] 
Ejercicio: [3] 
-->



<!ELEMENT panel (aeropuerto, vuelos)>
<!ATTLIST panel fecha CDATA #REQUIRED>

<!ELEMENT aeropuerto (#PCDATA)>

<!ELEMENT vuelos (vuelo+)>

<!ELEMENT vuelo (origen, destino, hora_salida, hora_llegada, compania, diario?)>
<!ATTLIST vuelo codigo ID #REQUIRED
                estado (C | E | R) "E">

<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>
<!ELEMENT compania (#PCDATA)>
<!ELEMENT diario EMPTY>

=== MikelTESP/Lenguaje-de-Marcas/EJ 3 Validacion XML DTD 2.xml
<!-- 
Nombre: [MikelTorremocha] 
Curso: [DAM 1] 
Fecha: [2/4/2025] 
Ejercicio: [3] 
-->



<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel SYSTEM "Panel.dtd">
<panel fecha="2025-04-03">
    <aeropuerto>Nombre del Aeropuerto</aeropuerto>
    <vuelos>
        <vuelo codigo="AA123" estado="E">
            <origen>Madrid</origen>
            <destino>Barcelona</destino>
            <hora_salida>14:30</hora_salida>
            <hora_llegada>15:45</hora_llegada>
            <compania>Iberia</compania>
            <diario/>
        </vuelo>
        <vuelo codigo="BB456" estado="R">
            <origen>Par√≠s</origen>
            <destino>Lisboa</destino>
            <hora_salida>16:00</hora_salida>
            <hora_llegada>18:10</hora_llegada>
            <compania>Air France</compania>
        </vuelo>
    </vuelos>
</panel>
